### ISSUE TITLE
Series with 453 images does not work

### ISSUE THREAD

**Issue by 6Beaufort** [ivmartel/dwv-orthanc-plugin#9]
shows 
   Error 500: Server Error
   Request Too Large

is there a limit or a config file to increase the limit?

BTW, if I pull the newest version of this plugin, does it contain the newest version of dwv automatically or is there an extra step required?

best
Mumin

**Comment by ivmartel** [comment]
This is a server error, not sure if it is a Orthanc limit. I will try and recreate it to get a better idea.
The latest version of this plugin uses dwv 0.10.0, I need to update it to the latest 0.10.1.

**Comment by rjosest** [comment]
Hi,

I run into the same problem when using the plug in in Orthanc. I post the error in the Orthanc user list and I got the following response from Sebastien (see below).

It looks like the best work around for this is to switch to POST request. Is POST request a future feature?

Thanks a lot
/R

—— Email from Orthanc user group — 

"Hello,

This problem is related to the DWV plugin, as this viewer receives all the instances to display as HTTP GET arguments:
https://en.wikipedia.org/wiki/Query_string

But, such URL-encoded strings are limited to 8000 characters for maximal compatibility: 
https://en.wikipedia.org/wiki/Query_string#Compatibility_issues

As any Orthanc identifier has a length of 44 characters, this limits the size of the series DWV can display to about 180 instances (= 8000/44). According to this rough computation, any series that is made of more than 180 instances will result in an error.

At this point, you have two possibilities:
Ask Yves (DWV's author) to support POST requests instead of GET requests. This will remove any limitation on the number of instances in the series.
Resort to the official Web viewer plugin for Orthanc that supports series of arbitrary length: http://www.orthanc-server.com/static.php?page=web-viewer
HTH,
Sébastien-"

**Comment by ivmartel** [comment]
I'm looking into receiving requests via POST, see ivmartel/dwv#130, but I need to investigate it further... Any help appreciated!

**Comment by rjosest** [comment]
Happy to help with this effort. I'm not an expert in Web technologies but I can dig in further with some pointers. I'm not familiar with the dwv package.

**Comment by ivmartel** [comment]
Link to the google groups thread: [Error 500: Server Error Request Too Large](https://groups.google.com/forum/#!topic/orthanc-users/2-aa4j28m-Y).
